sudo: required
language: php
addons:
  chrome: stable
  mariadb: 10.4
dist: bionic
env:
  global:
    APP_ENV=testing
matrix:
  fast_finish: true
  include:
  - php: 7.4
    env: SKIP_STYLE_CHECK=1
  - php: 7.3
    env: SKIP_UNIT_CHECK=1 BROWSER_TEST=1 CHROME_HEADLESS=1
  - php: 7.2
    env: SKIP_STYLE_CHECK=1 EXECUTE_BUILD_DOCS=true

cache:
  directories:
    - vendor
    - $HOME/.cache/pip
    - $HOME/.composer/cache

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -f
  - sudo apt-get install -y fping python3-pip python3-setuptools
  - sudo apt-get build-dep snmp
  - curl -LO https://netcologne.dl.sourceforge.net/project/net-snmp/net-snmp/5.8/net-snmp-5.8.tar.gz
  - tar xvf net-snmp-5.8.tar.gz
  - cd net-snmp-5.8
  - ./configure --prefix=/usr
  - make
  - sudo make install
  - cd ..
  - sudo mysql -e "CREATE USER 'root'@'%' IDENTIFIED BY ''; ALTER USER 'root'@'localhost' IDENTIFIED BY ''; GRANT ALL PRIVILEGES on *.* TO 'root'@'%'; FLUSH PRIVILEGES;";
  - sudo mysql -e 'CREATE DATABASE librenms_phpunit_78hunjuybybh CHARACTER SET utf8 COLLATE utf8_unicode_ci;'
  - cp tests/config/config.test.php config.php
  - sudo cp php.ini /etc/php.ini

install:
  - travis_retry composer install --no-interaction --prefer-dist --no-suggest
  - pip3 install --user snmpsim
  - pip install --user mysql-python pylint

after_failure:
  - tail /tmp/snmpsimd.log

before_script:
  - phpenv config-rm xdebug.ini
  - test -z "$BROWSER_TEST" || php artisan dusk:update --detect
  - test -z "$BROWSER_TEST" || php artisan serve --env=dusk.testing  2>/dev/null &

script:
  - php ./validate.php
  - set -e
  - php scripts/pre-commit.php -o ftos --fail-fast
  - test -z "$BROWSER_TEST" || php artisan config:clear
  - test -z "$BROWSER_TEST" || php artisan dusk
  - bash -n daily.sh
  - pylint -E poller-wrapper.py discovery-wrapper.py services-wrapper.py
  - bash scripts/deploy-docs.sh
  - set +e
